# Generated by Django 4.2.5 on 2023-09-16 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lasts_edit', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('name', models.CharField(max_length=64)),
                ('desc', models.TextField(default='-')),
                ('status', models.IntegerField(choices=[(1, 'developing'), (2, 'finished'), (3, 'letter'), (4, 'for got')], default=1)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('finish_date', models.DateTimeField()),
                ('repo', models.URLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='TaskManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.project')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=128)),
                ('task_desc', models.TextField()),
                ('task_status', models.BooleanField(default=False)),
                ('task_management', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.taskmanagement')),
            ],
        ),
    ]
