# Generated by Django 4.2.5 on 2023-09-16 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('desc', models.TextField(default='-')),
                ('status', models.IntegerField(choices=[(1, 'new'), (2, 'in progress'), (3, 'completed')], default=1)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=9)),
                ('start_data', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('repo', models.URLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=128)),
                ('task_desc', models.TextField()),
                ('task_status', models.BooleanField(default=False)),
                ('task_management', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.taskmanagement')),
            ],
        ),
    ]
