# Generated by Django 4.2.5 on 2023-09-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='end_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start_data',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
