# Generated by Django 4.2.5 on 2023-09-17 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_end_date_task_start_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='start_data',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_data',
            field=models.DateTimeField(null=True),
        ),
    ]
