# Generated by Django 4.2.5 on 2023-09-17 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_project_start_data_alter_task_start_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='start_data',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='start_data',
            new_name='start_date',
        ),
    ]
